ASoC: wcd9xxx-common-v2: Fix gcc-10 restrict error
Fix the following error by using "scnprintf" instead of "snprintf":

../sound/soc/codecs/wcd9xxx-common-v2.c: In function ‘state_to_str.constprop’:
../sound/soc/codecs/wcd9xxx-common-v2.c:272:9: error: ‘snprintf’ argument 4 overlaps destination object ‘buf’ [-Werror=restrict]
  272 |   cnt = snprintf(buf, buflen - cnt - 1, "%s%s%s", buf,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  273 |           buf[0] == '\0' ? "[" : "|",
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  274 |           states[i]);
      |           ~~~~~~~~~~

Signed-off-by: Planet-X <planetx.dev@gmail.com>