power: qpnp-fg: Fix gcc-10 restrict error
Fix the following error by using "scnprintf" instead of "snprintf":

../drivers/power/qpnp-fg.c: In function ‘restore_cycle_counter’:
../drivers/power/qpnp-fg.c:3386:3: error: ‘snprintf’ argument 4 overlaps destination object ‘ccInfo’ [-Werror=restrict]
 3386 |   snprintf(ccInfo, sizeof(ccInfo), "%s%d, ", ccInfo, chip->cyc_ctr.count[i]);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/power/qpnp-fg.c:3373:7: note: destination object referenced by ‘restrict’-qualified argument 1 was declared here
 3373 |  char ccInfo[128] = "";
      |       ^~~~~~

Signed-off-by: Planet-X <planetx.dev@gmail.com>